[build]
  base = "frontend"          # your frontend folder
  publish = "dist"           # Vite default build folder
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
